# See Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions:
        patterns: [ "*" ]
    reviewers:
      - "stuartmorgan"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
    # Updating patch versions for "github-actions" is too chatty.
    # See https://github.com/flutter/flutter/issues/158350.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Android example apps.
  - package-ecosystem: "gradle"
    directories:
      - /packages/vector_math/example/android/app
    commit-message:
      prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    labels:
      - "autosubmit"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
