# Copyright 2026 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Workflow to analyze and test all packages against a matrix of Dart versions.
#
# To run locally:
#     gh act pull_request
name: Multi-Version

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    analyze:
        name: Analyze and Test - Dart ${{ matrix.dart-sdk }}
        
        # This creates a separate job for every version in the list
        strategy:
            matrix:
                dart-sdk: [ 3.10.7, 3.11.5, main ]
            fail-fast: false # Continues other versions even if one fails

        runs-on: ubuntu-latest

        steps:
            - name: Set up repository and tooling
              uses: ./.github/actions/set-up-repo
              with:
                  dart-sdk: ${{ matrix.dart-sdk }}

            - name: Run Dart unit tests
              run: |
                  dart pub global run flutter_plugin_tools test

            - name: Run analyze
              run: |
                  dart pub global run flutter_plugin_tools analyze
