name: release
on:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  release:
    if: github.repository_owner == 'flutter'
    name: release
    permissions:
      # Release needs to push a tag back to the repo.
      contents: write
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of the repo.
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0 # Fetch all history so the tool can get all the tags to determine version.
        persist-credentials: false
    # Set up the latest stable release of Dart and tooling.
    - name: Set up environment and tooling
      id: setup
      uses: ./.github/actions/set-up-repo
      with:
        dart-sdk: 3.12.0

    # Give some time for checks to start becoming populated.
    # Because of latency in Github Webhooks, any checks that don't use GitHub
    # Actions may be delayed.
    - name: Give webhooks a minute
      run: sleep 60s
      shell: bash

    # In flutter/packages, there's a step here to wait for a specific LUCI
    # test to check in. Since this repo currently doesn't use LUCI that's not
    # here, but if any LUCI tests are added this should be updated to match
    # flutter/packages to avoid races where the next steps run before LUCI has
    # started.

    # Release should only happen if/when all other checks have passed.
    - name: Wait on all tests
      uses: lewagon/wait-on-check-action@96d9100b431964d10e0136aff8b9ccb92470505e
      with:
        ref: ${{ github.sha }}
        running-workflow-name: 'release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 180 # seconds
        allowed-conclusions: success,neutral
        # verbose:true will produce too many logs that hang github actions web UI.
        verbose: false

    - name: Configure Git
      run: |
        gh auth setup-git
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
    - name: run release
      run: |
        dart pub global run flutter_plugin_tools publish --all-changed --base-sha=HEAD~ --skip-confirmation --remote=origin
      env:
        PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
