# Copyright 2026 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Workflow to run repo best practice validations.
#
# To run locally:
#     gh act pull_request
name: Validate Repository

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    analyze:
        name: validate

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Dart
              uses: dart-lang/setup-dart@v1
              with:
                  sdk: main

            - name: Set up repo tooling
              run: |
                  # This should always use a pinned version to avoid out-of-band breakage.
                  dart pub global activate flutter_plugin_tools 0.14.1

            - name: Validate repository
              run: |
                  dart pub global run flutter_plugin_tools validate
