# Copyright 2026 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Workflow to run repo best practice validations.
#
# To run locally:
#     gh act pull_request
name: Validate Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: validate

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up environment and tooling
        id: setup
        uses: ./.github/actions/set-up-repo
        with:
          dart-sdk: main

      # For pre-submit, check for missing or breaking changes that don't have a
      # corresponding override label.
      # For post-submit, ignore platform interface breaking version changes and
      # missing version/CHANGELOG detection since PR-level overrides aren't available
      # in post-submit.
      - name: Run 'validate' for general repo best practices
        if: ${{ !cancelled() && steps.setup.outcome == 'success' }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            dart pub global run flutter_plugin_tools validate --ignore-platform-interface-breaks
          else
            dart pub global run flutter_plugin_tools validate --check-for-missing-changes --pr-labels="$(gh api --jq '.labels.[].name' /repos/flutter/core-packages/pulls/${{ github.event.number }} | paste -sd ',' -)"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run 'format' to check for formatting violations
        if: ${{ !cancelled() && steps.setup.outcome == 'success' }}
        run: |
          dart pub global run flutter_plugin_tools format --fail-on-change --no-swift

      - name: Run 'update-excerpts' to check for outdated README snippets
        if: ${{ !cancelled() && steps.setup.outcome == 'success' }}
        run: |
          dart pub global run flutter_plugin_tools update-excerpts

      - name: Run 'license-check' to check for license issues
        if: ${{ !cancelled() && steps.setup.outcome == 'success' }}
        run: |
          dart pub global run flutter_plugin_tools license-check

      # This is a relatively slow test, so keep it last.
      - name: Run 'publish-check' to make sure everything is in a publishable state
        if: ${{ !cancelled() && steps.setup.outcome == 'success' }}
        run: |
          dart pub global run flutter_plugin_tools publish-check --allow-pre-release
