# Copyright 2026 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Workflow to run repo best practice validations.
#
# To run locally:
#     gh act pull_request
name: Validate Repository

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    analyze:
        name: validate

        runs-on: ubuntu-latest

        steps:
            - name: Set up repository and tooling
              uses: ./.github/actions/set-up-repo
              with:
                  dart-sdk: main

            - name: Run 'validate' for general repo best practices
              run: |
                  dart pub global run flutter_plugin_tools validate

            - name: Run 'format' to check for formatting violations
              run: |
                  dart pub global run flutter_plugin_tools format --fail-on-change --no-swift

            - name: Run 'update-excerpts' to check for outdated README snippets
              run: |
                  dart pub global run flutter_plugin_tools update-excerpts

            - name: Run 'license-check' to check for license issues
              run: |
                  dart pub global run flutter_plugin_tools license-check

            # This is a relatively slow test, so keep it last.
            - name: Run 'publish-check' to make sure everything is in a publishable state
              run: |
                  dart pub global run flutter_plugin_tools publish-check --allow-pre-release
